#!/usr/bin/env bash
# Usage: bash scripts/dev.sh  (or: make dev)
# Starts local Supabase stack, writes .env.local, then starts Next.js.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# ── 1. Start local Supabase ─────────────────────────────────────────────────
echo "▶  Starting Supabase local stack (first run pulls Docker images, ~2–3 min)..."
npx supabase start

# ── 2. Extract credentials and write .env.local ─────────────────────────────
echo ""
echo "▶  Writing .env.local..."

STATUS=$(npx supabase status -o env 2>/dev/null)

get_val() { echo "$STATUS" | grep "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }

SB_URL=$(get_val API_URL)
SB_ANON=$(get_val ANON_KEY)
SB_SVC=$(get_val SERVICE_ROLE_KEY)
SB_DB=$(get_val DB_URL)

cat > "$ROOT/.env.local" << EOF
# Auto-generated by scripts/dev.sh — do not edit manually
# Supabase local stack
SUPABASE_URL=${SB_URL}
SUPABASE_ANON_KEY=${SB_ANON}
SUPABASE_SERVICE_ROLE_KEY=${SB_SVC}
DATABASE_URL=${SB_DB}
EOF

echo "   SUPABASE_URL             = ${SB_URL}"
echo "   Studio (table viewer)    = http://127.0.0.1:54323"
echo "   .env.local written ✓"
echo ""

# ── 3. Start Next.js dev server ─────────────────────────────────────────────
echo "▶  Starting Next.js dev server..."
echo ""
npm run dev
