#!/usr/bin/env bash
# Initial setup for a fresh Hetzner VPS (Ubuntu 24.04 LTS).
# Run once as root immediately after provisioning.
#
# Usage on server:
#   curl -fsSL https://raw.githubusercontent.com/karadyaur/kara3d/main/scripts/server-setup.sh | bash
# Or copy and run:
#   scp scripts/server-setup.sh root@<ip>:/tmp/
#   ssh root@<ip> bash /tmp/server-setup.sh

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run as root"; exit 1; }

DEPLOY_USER="deploy"
APP_DIR="/opt/kara3d"

G='\033[0;32m'; N='\033[0m'; B='\033[1m'
ok() { echo -e "  ${G}✓${N} $*"; }
h()  { echo -e "\n${B}$*${N}"; }

h "1. System update"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw fail2ban unattended-upgrades apt-transport-https
ok "Packages updated"

h "2. Deploy user"
if ! id "$DEPLOY_USER" &>/dev/null; then
  useradd -m -s /bin/bash "$DEPLOY_USER"
  ok "User '$DEPLOY_USER' created"
else
  ok "User '$DEPLOY_USER' already exists"
fi
usermod -aG sudo "$DEPLOY_USER"

# Copy root's SSH authorized_keys so the deploy user can be reached by CI
mkdir -p /home/${DEPLOY_USER}/.ssh
if [[ -f /root/.ssh/authorized_keys ]]; then
  cp /root/.ssh/authorized_keys /home/${DEPLOY_USER}/.ssh/authorized_keys
  chown -R ${DEPLOY_USER}:${DEPLOY_USER} /home/${DEPLOY_USER}/.ssh
  chmod 700 /home/${DEPLOY_USER}/.ssh
  chmod 600 /home/${DEPLOY_USER}/.ssh/authorized_keys
  ok "SSH keys copied to '$DEPLOY_USER'"
else
  echo "  ! No /root/.ssh/authorized_keys — add SSH key manually to /home/${DEPLOY_USER}/.ssh/authorized_keys"
fi

h "3. Docker"
if ! command -v docker &>/dev/null; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  ok "Docker installed"
else
  ok "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
fi
usermod -aG docker "$DEPLOY_USER"
systemctl enable --now docker
ok "Docker enabled (deploy user added to docker group)"

h "4. Firewall (UFW)"
ufw --force reset > /dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp  comment "SSH"
ufw allow 80/tcp  comment "HTTP"
ufw allow 443/tcp comment "HTTPS"
ufw --force enable > /dev/null
ok "UFW: allow 22, 80, 443 — deny everything else"

h "5. Fail2ban"
systemctl enable --now fail2ban
ok "Fail2ban active"

h "6. SSH hardening"
SSHD=/etc/ssh/sshd_config
cp "$SSHD" "${SSHD}.bak"
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/'  "$SSHD"
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/'                "$SSHD"
sed -i 's/^#\?X11Forwarding.*/X11Forwarding no/'                    "$SSHD"
sed -i 's/^#\?MaxAuthTries.*/MaxAuthTries 3/'                       "$SSHD"
systemctl restart ssh
ok "SSH: passwords disabled, root login disabled, max 3 auth tries"

h "7. Automatic security updates"
cat > /etc/apt/apt.conf.d/99unattended-custom << 'EOF'
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
EOF
systemctl enable --now unattended-upgrades
ok "Unattended security upgrades enabled"

h "8. App directory"
mkdir -p "$APP_DIR"
chown "${DEPLOY_USER}:${DEPLOY_USER}" "$APP_DIR"
ok "App directory: $APP_DIR (owner: $DEPLOY_USER)"

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${G}${B}Server ready!${N}"
echo ""
echo "Next steps (run from your local machine):"
echo ""
echo "  # 1. Copy environment variables to server"
echo "  scp .env ${DEPLOY_USER}@<server-ip>:${APP_DIR}/"
echo ""
echo "  # 2. Copy SSL certs (generated by 'make cf-setup')"
echo "  ssh ${DEPLOY_USER}@<server-ip> sudo mkdir -p /etc/ssl/kara3d"
echo "  scp /etc/ssl/kara3d/* ${DEPLOY_USER}@<server-ip>:/tmp/"
echo "  ssh ${DEPLOY_USER}@<server-ip> sudo mv /tmp/*.pem /etc/ssl/kara3d/"
echo ""
echo "  # 3. Add GitHub Secrets (Settings → Secrets → Actions):"
echo "     SSH_HOST        = <server-ip>"
echo "     SSH_USER        = ${DEPLOY_USER}"
echo "     SSH_PRIVATE_KEY = <private key that matches authorized_keys>"
echo ""
echo "  # 4. Push to main — GitHub Actions deploys automatically"
echo ""
